before_script:
- npm install -g bower gulp
- echo -e "StrictHostKeyChecking no\n" >> ~/.ssh/config
- bower install -f
- gulp build
language: node_js
node_js:
- '0.10'
deploy:
  provider: divshot
  api_key:
    secure: lJGC3XoxvkPotmkkMQ2TQ8aR3DAMBbaxg3XtneLzegTox/bqVZzu/inIvee98vvi4nRy1N7qmD2DC9BGhEtCkPB/xYRhCcH8FlkByyO65FeGhH6rviLbpzhtACBr4n8y++TG7eEziojIi49jdPX/Z/uOpqL0zMsjSOKXJw8j3pE=
  skip_cleanup: true
  environment: production
  on:
    repo: microservicos/microservicos-site
